require('core.plugin.lualine')
require('core.plugin.nvim-tree')
require('core.plugin.treesitter')
require('core.plugin.lsp')
require('core.plugin.completions')
require('core.plugin.jdtls')
require('core.plugin.rust-tools')
require('core.plugin.create-java-project')
